apiVersion: v1
kind: Service
metadata:
  name: server-a
spec:
  selector:
    app: server-a
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081      # porta esterna (deve essere tra 30000 e 32767)
  type: NodePort
