apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-b-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: server-b
  template:
    metadata:
      labels:
        app: server-b
    spec:
      containers:
        - name: server-b
          image: server-b:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
